### ISSUE TITLE
[Bug] Phone field not showing some numbers

### ISSUE THREAD

**Issue by sharat-rhinofish** [Laravel-Backpack/community-forum#1148]
# Bug report

### What I did

I have created a phone field in the database which is a varchar field.

In the Crud Controller, I have the following in the setupShowOperation function:
CRUD::column('phone')->type('phone')

In the same Crud Controller, I have the following in the setupCreateOperation function:
CRUD::field('phone')->type('phone')

I am entering the following phone number: +1 855-476-7674
When I save this number, I can see that the database shows the correct phone value of +18554767674
However, when I come back to Edit the entity, the phone shows up as "74" instead of the entered value.
The preview screen shows the correct phone number as +18554767674 with the tel: hyperlink.

The edit functionality is somehow not showing the right phone number. Note that with some other phone numbers like 708-670-4308, this works fine.

php artisan backpack:version results below.
### PHP VERSION:
8.2.20

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pcov, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, swoole, Zend OPcache, xdebug

### LARAVEL VERSION:
11.22.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.34
backpack/generators: v4.0.6
backpack/permissionmanager: 7.2.1
backpack/pro: 2.0.0
backpack/theme-tabler: 1.2.13

**Comment by tabacitu** [comment]
Hi @sharat-rhinofish ,

Jorge just pushed a fix to the bug. It was just a matter of updating the JS library. Please run `composer update`, that should fix it. If you have it in production too, there it needs you to refresh your assets too (`php artisan basset:clear && php artisan basset:cache`).

Let us know if that doesn't fix it, and we'll reopen.

Thanks for letting us know about it.
Cheers!

**Comment by sharat-rhinofish** [comment]
Hi Cristian,

 

I ran composer update and also ran php artisan basset:clear && php artisan basset:cache

However, the problem still seems to be there.

 

*** Composer update results

Loading composer repositories with package information

Updating dependencies                                 

Lock file operations: 0 installs, 9 updates, 1 removal

  - Removing symfony/polyfill-php72 (v1.30.0)

  - Upgrading nyholm/psr7 (1.8.1 => 1.8.2)

  - Upgrading symfony/polyfill-ctype (v1.30.0 => v1.31.0)

  - Upgrading symfony/polyfill-intl-grapheme (v1.30.0 => v1.31.0)

  - Upgrading symfony/polyfill-intl-idn (v1.30.0 => v1.31.0)

  - Upgrading symfony/polyfill-intl-normalizer (v1.30.0 => v1.31.0)

  - Upgrading symfony/polyfill-mbstring (v1.30.0 => v1.31.0)

  - Upgrading symfony/polyfill-php80 (v1.30.0 => v1.31.0)

  - Upgrading symfony/polyfill-php83 (v1.30.0 => v1.31.0)

  - Upgrading symfony/polyfill-uuid (v1.30.0 => v1.31.0)

Writing lock file

Installing dependencies from lock file (including require-dev)

Package operations: 0 installs, 9 updates, 1 removal

  - Downloading symfony/polyfill-ctype (v1.31.0)

  - Downloading symfony/polyfill-php83 (v1.31.0)

  - Downloading symfony/polyfill-mbstring (v1.31.0)

  - Downloading symfony/polyfill-intl-normalizer (v1.31.0)

  - Downloading symfony/polyfill-intl-grapheme (v1.31.0)

  - Downloading symfony/polyfill-php80 (v1.31.0)

  - Downloading symfony/polyfill-uuid (v1.31.0)

  - Downloading symfony/polyfill-intl-idn (v1.31.0)

  - Downloading nyholm/psr7 (1.8.2)

  - Removing symfony/polyfill-php72 (v1.30.0)

  - Upgrading symfony/polyfill-ctype (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading symfony/polyfill-php83 (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading symfony/polyfill-mbstring (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading symfony/polyfill-intl-normalizer (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading symfony/polyfill-intl-grapheme (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading symfony/polyfill-php80 (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading symfony/polyfill-uuid (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading symfony/polyfill-intl-idn (v1.30.0 => v1.31.0): Extracting archive

  - Upgrading nyholm/psr7 (1.8.1 => 1.8.2): Extracting archive

***

 

***@***.***:/var/www/html# php artisan backpack:version

### PHP VERSION:

8.2.20

 

### PHP EXTENSIONS:

Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pcov, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, swoole, Zend OPcache, xdebug

 

### LARAVEL VERSION:

11.22.0.0

 

### BACKPACK PACKAGE VERSIONS:

backpack/basset: 1.3.6

backpack/crud: 6.7.34

backpack/generators: v4.0.6

backpack/permissionmanager: 7.2.1

backpack/pro: 2.0.0

backpack/theme-tabler: 1.2.13

 

Any specific file I should be looking for to see the update.

 

Heartful Regards,

Sharat

 

 

From: Cristian Tăbăcitu ***@***.***>
Reply to: Laravel-Backpack/community-forum ***@***.***>
Date: Tuesday, 10 September 2024 at 6:57 PM
To: Laravel-Backpack/community-forum ***@***.***>
Cc: Sharat Hegde ***@***.***>, Mention ***@***.***>
Subject: Re: [Laravel-Backpack/community-forum] [Bug] Phone field not showing some numbers (Issue #1148)

 

Hi @sharat-rhinofish ,

Jorge just pushed a fix to the bug. It was just a matter of updating the JS library - that's where the bug was. Please run composer update, that should fix it. If you have it in production too, there it needs you to refresh your assets too (php artisan basset:clear && php artisan basset:cache).

Let us know if that doesn't fix it, and we'll reopen.

Thanks for letting us know about it.
Cheers!

**Comment by pxpm** [comment]
Hello @sharat-rhinofish 

You probably need to work with the phone library configurations. Most of the time, the configs that need some tweak are: 
```php
'separateDialCode'
'nationalMode'
'autoInsertDialCode'
'autoHideDialCode'
```

Play with them while configuring your phone field, eg:
```php
CRUD::field('phone')
            ->type('phone')
            ->size(6)
            ->config([
                'separateDialCode' => false,
                'nationalMode' => false,
                'autoInsertDialCode' => true,
                'autoHideDialCode' => true,
            ]);
```

Let me know if that helps 👍

**Comment by sharat-rhinofish** [comment]
Hi Pedro,

 

Thank you. I have realized that I have not done an upgrade to Backpack Pro 2.0 as my updates due date is over. I need to renew, upgrade Backpack Pro to try this out. Good to know that the issue is resolved.

 

Heartful Regards,

Sharat

 

 

From: Pedro Martins ***@***.***>
Reply to: Laravel-Backpack/community-forum ***@***.***>
Date: Monday, 16 September 2024 at 8:10 PM
To: Laravel-Backpack/community-forum ***@***.***>
Cc: Sharat Hegde ***@***.***>, Mention ***@***.***>
Subject: Re: [Laravel-Backpack/community-forum] [Bug] Phone field not showing some numbers (Issue #1148)

 

Hello @sharat-rhinofish

You probably need to work with the phone library configurations. Most of the time, the configs that need some tweak are:

'separateDialCode'
'nationalMode'
'autoInsertDialCode'
'autoHideDialCode'
Play with them while configuring your phone field, eg:

CRUD::field('phone')
            ->type('phone')
            ->size(6)
            ->config([
                'separateDialCode' => false,
                'nationalMode' => false,
                'autoInsertDialCode' => true,
                'autoHideDialCode' => true,
            ]);
Let me know if that helps 👍

**Comment by pxpm** [comment]
Thanks for getting back. 🙏 

I will close this for now then, if you experience issues after the update please let us know 👍
