### ISSUE TITLE
"Invalid parameter number" error after server move

### ISSUE THREAD

**Issue by netbbe** [Laravel-Backpack/community-forum#348]
Hi!

One of our CRUD controllers is broken after we've moved from one server (ServerPilot/Apache+MySQL) to another (RunCloud/nginx+MariaDB). I don't know if this has anything to do with the problem. The error occurs when opening one of our CRUD controllers. No data appears, and the "Error loading page. Please refresh the page." error is briefly shown. Checking the Network tab shows that the /search request receives an error, pointing to Backpack's listing function.

This works fine on our old server, which runs the same version of Laravel (v8) and Backpack (v5). And we can copy this full query and execute it without problems in PhpMyAdmin. We tried upgrading Laravel to v9, but it's not helping.

We need to figure out where to search. Any advice?

```
{
    "message": "**SQLSTATE[HY093]: Invalid parameter number** (SQL: select count(*) as total_rows from (select `employees`.`id`, COUNT(DISTINCT `els`.`trainingmodule_level_id`) AS completed from `employees` inner join `department_employee` as `de` on `de`.`employee_id` = `employees`.`id` inner join `departments` as `d` on `d`.`id` = `de`.`department_id` left join (`employee_level_status` as `els` inner join `trainingmodule_levels` as `tml` on `tml`.`id` = `els`.`trainingmodule_level_id` and `tml`.`trainingmodule_id` = 1 and `tml`.`is_required` = 1) on `els`.`employee_id` = `employees`.`id` and `els`.`status` = 3 where `employees`.`delete_date` is null group by `employees`.`id`) as `employees_aggregator`)",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 712,
    "trace": [
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 672,
            "function": "runQueryCallback",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 410,
            "function": "run",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2591,
            "function": "cursor",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "function": "Illuminate\\Database\\Query\\{closure}",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php",
            "line": 399,
            "function": "valid",
            "class": "Generator",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Query.php",
            "line": 273,
            "function": "first",
            "class": "Illuminate\\Support\\LazyCollection",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Query.php",
            "line": 207,
            "function": "getCountFromQuery",
            "class": "Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Query.php",
            "line": 220,
            "function": "**getQueryCount**",
            "class": "Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/backpack/crud/src/app/Http/Controllers/Operations/ListOperation.php",
            "line": 101,
            "function": "**getFilteredQueryCount**",
            "class": "Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "**search**",
            "class": "App\\Http\\Controllers\\Admin\\TraineeCrudController",
            "type": "->"
        },
        {
            "file": "/home/onebonsai-vip/webapps/onebonsai-vip/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
```

**Comment by netbbe** [comment]
Here's the output:

```
### PHP VERSION:
PHP 8.1.12 (cli) (built: Nov  2 2022 08:07:11) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.83.27@e1afe088b4ca613fb96dc57e6d8dbcb8cc2c6b49

### BACKPACK VERSION:
5.4.13@af521f3bfed6de5c41811289d901c6c66f8242e2

```

**Comment by netbbe** [comment]
> Hey @netbbe thanks for the report.
> 
> Can you do a `php artisan backpack:version` and give me the output?
> 
> Cheers

Is this something you can help with?

**Comment by pxpm** [comment]
Hello @netbbe , sorry for my absence in this issue. 

As a workaround while I try to nail down the issue you can do `$this->crud->setOperationSetting('showEntryCount', false)` in your `setupListOperation`. 

The only difference I can see would be from mysql -> mariadb. Any chance you can try running it with mysql instead of mariadb in your new instance ? 

If you can't I will try to replicate it on my side, but it could be a combination of this specific query and the engine, because I assume your other cruds work fine ? 

Cheers

**Comment by netbbe** [comment]
Thanks @pxpm! The showEntryCount disabling made the error disappear, so it's an acceptable temporary workaround.

Switching from MariaDB to MySQL is impossible with this server management service (=RunCloud).

**Comment by netbbe** [comment]
Is this something that can receive a higher priority? We're still using the workaround, but it's disabling some Backpack features.
It's hurting our software and changing our server setup is a monumental and painful task.

**Comment by pxpm** [comment]
Hey @netbbe 
Sorry I haven't had time to work this out. 

In the meanwhile since you opened this issue we merged some code aimed to fix issues related with this entry count. 

Maybe as a side effect we fixed this issue? 
Did you upgrade to the latest version of backpack package?

Can you let me know if the issue still persists in the latest version?

Cheers

**Comment by netbbe** [comment]
Hi Pedro,

Unfortunately, the problem persists. We've also updated our version of Laravel to v10 (from v8), but that doesn't make a difference. The error looks different now. 'Invalid parameter number' is now 'Column already exists'.
`{
    "message": "SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' (Connection: tenant, SQL: select count(*) as total_rows from (select *, COUNT(DISTINCT `els`.`trainingmodule_level_id`) AS completed, COUNT(`ts`.id) AS `count_sessions` from `employees` inner join `department_employee` as `de` on `de`.`employee_id` = `employees`.`id` left join `departments` as `d` on `d`.`id` = `de`.`department_id` left join `trainingsessions` as `ts` on `ts`.`employee_id` = `employees`.`id` left join (`employee_level_status` as `els` inner join `trainingmodule_levels` as `tml` on `tml`.`id` = `els`.`trainingmodule_level_id` and `tml`.`trainingmodule_id` = 1 and `tml`.`is_required` = 1) on `els`.`employee_id` = `employees`.`id` and `els`.`status` = 3 left join `employee_milestones` as `em` on `em`.`employee_id` = `employees`.`id` left join `trainingmodule_milestone_trainingmodule` as `tmmtm` on `tmmtm`.`trainingmodule_milestone_id` = `em`.`training_module_milestone_id` where `employees`.`delete_date` is null group by `employees`.`id`) as `employees_aggregator`)",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 793,
    "trace": [
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 753,
            "function": "runQueryCallback",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
            "line": 489,
            "function": "run",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
            "line": 2912,
            "function": "cursor",
            "class": "Illuminate\\Database\\Connection",
            "type": "->"
        },
        {
            "function": "Illuminate\\Database\\Query\\{closure}",
            "class": "Illuminate\\Database\\Query\\Builder",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Collections/LazyCollection.php",
            "line": 460,
            "function": "valid",
            "class": "Generator",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Query.php",
            "line": 277,
            "function": "first",
            "class": "Illuminate\\Support\\LazyCollection",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Query.php",
            "line": 207,
            "function": "getCountFromQuery",
            "class": "Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/backpack/crud/src/app/Library/CrudPanel/Traits/Query.php",
            "line": 220,
            "function": "getQueryCount",
            "class": "Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/backpack/crud/src/app/Http/Controllers/Operations/ListOperation.php",
            "line": 101,
            "function": "getFilteredQueryCount",
            "class": "Backpack\\CRUD\\app\\Library\\CrudPanel\\CrudPanel",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "search",
            "class": "App\\Http\\Controllers\\Admin\\TraineeCrudController",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 43,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 260,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 205,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 798,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 141,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/backpack/crud/src/app/Http/Controllers/CrudController.php",
            "line": 44,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 162,
            "function": "Backpack\\CRUD\\app\\Http\\Controllers\\{closure}",
            "class": "Backpack\\CRUD\\app\\Http\\Controllers\\CrudController",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/spatie/laravel-permission/src/Middlewares/RoleMiddleware.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 180,
            "function": "handle",
            "class": "Spatie\\Permission\\Middlewares\\RoleMiddleware",
            "type": "->"
        },...`

The problem is caused by this "custom query", which is set up in setup():
`        $this->crud->query
                ->from('employees')
                ->join('department_employee AS de', 'de.employee_id', '=', 'employees.id')
                ->leftJoin('departments AS d', 'd.id', '=', 'de.department_id')
                ->leftJoin('trainingsessions AS ts', 'ts.employee_id', '=', 'employees.id')
                ->leftJoin('employee_level_status AS els', function ($join) use ($trainingModuleID) {
                    $join->on('els.employee_id', '=', 'employees.id')
                        ->where('els.status', 3)
                        ->join('trainingmodule_levels AS tml', function ($join) use ($trainingModuleID) {
                            $join->on('tml.id', '=', 'els.trainingmodule_level_id')
                            ->where('tml.trainingmodule_id', $trainingModuleID)
                            ->where('tml.is_required', 1);
                        });
                    })
                ->leftJoin('employee_milestones AS em', 'em.employee_id', '=', 'employees.id')
                ->leftJoin('trainingmodule_milestone_trainingmodule AS tmmtm', 'tmmtm.trainingmodule_milestone_id', '=', 'em.training_module_milestone_id')
                ->select('employees.*', DB::raw('COUNT(DISTINCT `els`.`trainingmodule_level_id`) AS completed'), DB::raw('COUNT(`ts`.id) AS `count_sessions`'))
                ->where("employees.delete_date", "=", NULL)
                ->groupBy('employees.id');`

**Comment by pxpm** [comment]
Hello @netbbe thanks for getting back to me 🙏 

Is quite a big query to debug 🐛 Let me try.

From the error given, plus the info you provided, I think the error may come from the `select('employees.*, ...)` (the one before the where and groupBy clauses).

The "raw count" as `count_sessions` may be the culprit here. 

Can you try it without that or write it `count('ts.id')`? 

```php
 select count(*) as total_rows from (select *, COUNT(DISTINCT 'els'.'trainingmodule_level_id') AS completed, COUNT('ts'.id) AS 'count_sessions' from 'employees' inner join 'department_employee' as 'de' on 'de'.'employee_id' = 'employees'.'id' left join 'departments' as 'd' on 'd'.'id' = 'de'.'department_id' left join 'trainingsessions' as 'ts' on 'ts'.'employee_id' = 'employees'.'id' left join ('employee_level_status' as 'els' inner join 'trainingmodule_levels' as 'tml' on 'tml'.'id' = 'els'.'trainingmodule_level_id' and 'tml'.'trainingmodule_id' = 1 and 'tml'.'is_required' = 1) on 'els'.'employee_id' = 'employees'.'id' and 'els'.'status' = 3 left join 'employee_milestones' as 'em' on 'em'.'employee_id' = 'employees'.'id' left join 'trainingmodule_milestone_trainingmodule' as 'tmmtm' on 'tmmtm'.'trainingmodule_milestone_id' = 'em'.'training_module_milestone_id' where 'employees'.'delete_date' is null group by 'employees'.'id') as 'employees_aggregator')",
```

Let me know. 

Cheers

**Comment by netbbe** [comment]
Hey @pxpm,

We removed the count_sessions and then without "COUNT('ts'.id) AS 'count_sessions'" altogether, but we're still seeing the same error. Current error with the full query:
```    "message": "SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' (Connection: tenant, SQL: select count(*) as total_rows from (select *, COUNT(DISTINCT `els`.`trainingmodule_level_id`) AS completed from `employees` inner join `department_employee` as `de` on `de`.`employee_id` = `employees`.`id` left join `departments` as `d` on `d`.`id` = `de`.`department_id` left join `trainingsessions` as `ts` on `ts`.`employee_id` = `employees`.`id` left join (`employee_level_status` as `els` inner join `trainingmodule_levels` as `tml` on `tml`.`id` = `els`.`trainingmodule_level_id` and `tml`.`trainingmodule_id` = 1 and `tml`.`is_required` = 1) on `els`.`employee_id` = `employees`.`id` and `els`.`status` = 3 left join `employee_milestones` as `em` on `em`.`employee_id` = `employees`.`id` left join `trainingmodule_milestone_trainingmodule` as `tmmtm` on `tmmtm`.`trainingmodule_milestone_id` = `em`.`training_module_milestone_id` where `employees`.`delete_date` is null group by `employees`.`id`) as `employees_aggregator`)",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "/home/vagrant/code/vrplatform/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 795,
```
Our current code:
```
        $this->crud->query
                ->from('employees')
                ->join('department_employee AS de', 'de.employee_id', '=', 'employees.id')
                ->leftJoin('departments AS d', 'd.id', '=', 'de.department_id')
                ->leftJoin('trainingsessions AS ts', 'ts.employee_id', '=', 'employees.id')
                ->leftJoin('employee_level_status AS els', function ($join) use ($trainingModuleID) {
                    $join->on('els.employee_id', '=', 'employees.id')
                        ->where('els.status', 3)
                        ->join('trainingmodule_levels AS tml', function ($join) use ($trainingModuleID) {
                            $join->on('tml.id', '=', 'els.trainingmodule_level_id')
                            ->where('tml.trainingmodule_id', $trainingModuleID)
                            ->where('tml.is_required', 1);
                        });
                    })
                ->leftJoin('employee_milestones AS em', 'em.employee_id', '=', 'employees.id')
                ->leftJoin('trainingmodule_milestone_trainingmodule AS tmmtm', 'tmmtm.trainingmodule_milestone_id', '=', 'em.training_module_milestone_id')
                ->select('employees.*', DB::raw('COUNT(DISTINCT `els`.`trainingmodule_level_id`) AS completed'))
                ->where("employees.delete_date", "=", NULL)
                ->groupBy('employees.id');
```

To recap, with showEntryCount disabled, it works fine.
```$this->crud->setOperationSetting('showEntryCount', false);```

**Comment by pxpm** [comment]
Ok .. Vagrant. 

Give me a few days, I also have other stuff to test in Vagrant and I plan to do it during next week.

I will try to replicate this in Vagrant.

**Comment by tabacitu** [comment]
Note - may be related to https://github.com/Laravel-Backpack/community-forum/issues/553

**Comment by pxpm** [comment]
I am closing this as I couldn't reproduce it. The issue is not closed, we can continue the conversation, but this would only be possible with a little bit more debug. 

Maybe if you can provide me a failing query without so many joins, try removing some of the joins, and not using `select(employers.*)` and select only the columns you need, I suspect that you are getting the id again there and the `$this->crud->query()` already have a `select(*)`.

I think it's similar to: https://github.com/Laravel-Backpack/community-forum/discussions/621#discussioncomment-6657750

Let me know if I can help you with something else. 🙏

**Comment by netbbe** [comment]
@pxpm, sorry for the delay. Summer gave us other priorities for a while.

We dove into this again, as it's now breaking more than just 1 CRUD. We found this a simple reproducible case:
In setup() of our CrudController:
```
CRUD::setModel(ModelA::class);
$this->crud->query->join('anothertable AS b', 'b.id,'=','table.id')->groupBy('b.some_id');
```
The combination of the join and the groupBy seems enough to break the CRUD listing. To make this fail, there must be at least one shared column name between these two tables.

We were also able to find the precise line that causes this: line 260 in Backpack\CRUD\app\Library\CrudPanel\Traits\Query.php:
```
        // select minimum possible columns for the count
        $minimumColumns = ($crudQuery->groups || $crudQuery->havings) ? '*' : $modelTable.'.'.$this->model->getKeyName();
        $subQuery->select($minimumColumns);
```
If you have a groupBy, it adds * as the "minimum column" which doesn't work with these joins where there are shared column names.

It seems you updated this in April of this year:  
https://github.com/Laravel-Backpack/CRUD/commit/61838f89b3a42bc97fab88f82fd859c8700b7e34

I believe #621 fixed it because they rewrote their code without the groupBy.

**Comment by pxpm** [comment]
Hey @netbbe I've pushed a change regarding this in the last version of backpack/crud.
Make sure you are running the last version, if the problem persists please open a new issue and I will take a look at it this week. 

Cheers
